WebUI/Models/ContactUs.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebUI.Models
{
    public class ContactUs : Entities.Concrete.ContactUs
    {
    }
}

WebUI/Controllers/ContactUsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Abstract;
using Microsoft.AspNetCore.Http;
using WebUI.Models;
using FeedBacks = Business.Constants.Messages;

namespace WebUI.Controllers
{
    public class ContactUsController : Controller
    {
        private IContactUsService _contactUsService;

        public ContactUsController(IContactUsService contactUsService)
        {
            _contactUsService = contactUsService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Entities.Concrete.ContactUs contactUs)
        {
            if (ModelState.IsValid)
            {
                var result = _contactUsService.Add(contactUs);

                if (result.Success)
                {
                    TempData["ContactSendMessageResult"] = result.Message;
                    return View();
                }
            }
            
            TempData["ContactSendMessageResult"] = FeedBacks.MessagesCanNotAdded;
            return View(contactUs);
        }

        [HttpGet]
        public IActionResult Messages()
        {
            if (HttpContext.Session.GetString("isUserLogin") != "true" || HttpContext.Session.GetInt32("userRole") == 1)
            {
                TempData["userIsNotLogin"] = "Yönetim Paneline Erişebilmek İçin Lütfen Giriş Yapınız!";
                return RedirectToAction("Login","Admin");
            }

            var result = _contactUsService.GetAll();
            if (result.Success)
            {
                ViewBag.messageStatus = result.Success;
                return View(result.Data);
            }

            ViewBag.messageStatus = result.Success;
            ViewBag.messagesError = result.Message;
            return View();
        }

        [HttpGet]
        public IActionResult DeleteMessage(int id)
        {
            if (HttpContext.Session.GetString("isUserLogin") != "true" || HttpContext.Session.GetInt32("userRole") == 1)
            {
                TempData["userIsNotLogin"] = "Yönetim Paneline Erişebilmek İçin Lütfen Giriş Yapınız!";
                return RedirectToAction("Login","Admin");
            }

            var message = _contactUsService.GetById(id);

            var result = _contactUsService.Delete(message.Data);
            if (result.Success)
            {
                TempData["messagesError"] = result.Message;
                return RedirectToAction("Messages");
            }

            TempData["messagesError"] = result.Message;
            return RedirectToAction("Messages");
        }
    }
}

WebUI/Views/ContactUs/Index.cshtml
@{
    ViewBag.Title = "Bize Ulaşın - Bisiklet Kliniği";
}

@model Entities.Concrete.ContactUs

<div class="container mt-4 Contact">
    <div class="row">

        <div class="col d-flex align-items-center">
            <address>
                <strong><i class="bi bi-geo-alt"></i> Adres:</strong> West Park Evleri, Ekinoba Mah Mustafa Kemal Bulvarı, Orhan Veli Sk. NO 1 D:3B, 34535 Büyükçekmece/İstanbul <br />
                <strong><i class="bi bi-telephone"></i> Telefon:</strong> 0507 082 51 82 <br />
                <strong><i class="bi bi-envelope"></i> E-Posta:</strong> bisikletklinigi@gmail.com <br />
            </address>
        </div>

        <div class="col">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3010.8821249683556!2d28.539938315728932!3d41.00595312751605!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14b55dc25d1e8249%3A0xe5bab9f5ef90918!2sBisiklet%20Klini%C4%9Fi%20Servis%20Ve%20Perakende%20Hizmeti!5e0!3m2!1str!2str!4v1614543558392!5m2!1str!2str" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
        </div>

    </div>

    <section class="align-center text-center">
        <div class="container align-items-center">
            <hr>
            <h2>İletişime Geçin</h2>
            <p>Düşüncelerinizi iletişim formuyla iletmekten çekinmeyin.</p>

            <div class="col-md-6" style="margin: auto">
                @if (TempData["ContactSendMessageResult"] != null)
                {
                    <hr />
                    <h1 style="color: red;">@TempData["ContactSendMessageResult"]</h1>
                    <hr />
                }
                <form method="POST" asp-controller="ContactUs" asp-action="Index" class="form-horizontal">
                    <div class="row mt-3">
                        <div class="col">
                            <div class="form-group">
                                <label asp-for="FirstName"></label>
                                <input asp-for="FirstName" class="form-control" placeholder="İsim">
                                <span asp-validation-for="FirstName"></span>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label asp-for="LastName"></label>
                                <input asp-for="LastName" class="form-control" placeholder="Soyisim">
                                <span asp-validation-for="LastName"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group mt-3">
                        <label asp-for="Email"></label>
                        <input asp-for="Email" class="form-control" placeholder="isimsoyisim@example.com">
                        <span asp-validation-for="Email"></span>
                    </div>
                    <div class="form-group mt-3">
                        <label asp-for="Message"></label>
                        <textarea asp-for="Message" class="form-control" placeholder="Buradan bir mesaj gönderebilirsiniz!"></textarea>
                        <span asp-validation-for="Message"></span>
                    </div>
                    <button type="submit" class="btn btn-danger btn-lg mt-3">Gönder</button>
                </form>

                <hr>
                <h3>Sosyal Medyada Biz</h3>
                <ul class="list-inline Social-links">
                    <li><a href="https://www.instagram.com/bisikletklinigi/" class="btn btn-default btn-lg"><i class="bi bi-instagram"></i> Instagram</a></li>
                    <li><a href="https://www.facebook.com/Bisiklet-Klini%C4%9Fi-Servis-Ve-Perakende-Hizmeti-106394701508459" class="btn btn-default btn-lg"><i class="bi bi-facebook"></i> Facebook</a></li>
                    <li><a href="https://twitter.com/BisikletKlinigi" class="btn btn-default btn-lg"><i class="bi bi-twitter"></i> Twitter</a></li>
                    <li><a href="https://www.youtube.com/channel/UCn7CSmPMeRYwIwv3jNKqqgA" class="btn btn-default btn-lg"><i class="bi bi-youtube"></i> Youtube</a></li>
                </ul>
            </div>

        </div>

    </section>


</div>

WebUI/Views/ContactUs/Messages.cshtml
@model List<Entities.Concrete.ContactUs>

@{
    Layout = "_AdminLayout";
}

@{
    ViewBag.Title = "Yönetim Paneli - Mesajlar";
}

@if (TempData["messagesError"] != null)
{
    <h1 class="text-center" style="color: red;">@TempData["messagesError"]</h1>
}

@if (ViewBag.messageStatus = false)
{
    <h1 class="text-center">@ViewBag.messagesError</h1>
}
else
{

<div class="container mt-4">
    <h2 class="m-2 text-center">Mesajlar</h2>
    
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            @foreach (var message in Model.OrderByDescending(x => x.Id))
            {
                <center>
                    <div class="col-md mb-4" style="text-align: left; max-width: 700px;">
                        <div class="row m-2">
                            <div class="col border border-3  rounded">
                                <span>@message.FirstName</span>
                            </div>
                            <div class="col border border-3  rounded">
                                <span>@message.LastName</span>
                            </div>
                        </div>
                        <div class="row border border-3 m-2 rounded">
                            <span>@message.Email</span>
                        </div>
                        <div class="row border border-3 m-2 rounded">
                            <p>@message.Message</p>
                        </div>
                        <div class="row m-2 text-center">
                            <div class="col-md-6"><a class="btn btn-success" href="mailto:@message.Email"><i class="bi bi-envelope-fill"></i> Kullanıcıya Mail Gönder</a></div>
                            <div class="col-md-6"><a class="btn btn-danger" href="/contactus/DeleteMessage/@message.Id"><i class="bi bi-envelope-fill"></i> Mesajı Sil</a></div>
                        </div>
                    </div>
                    <hr class="mb-4" style="max-width: 700px;"/>
                </center>
            }
        </div>
        <div class="col-md-2"></div>
    </div>
    
</div>
   
}